### PR TITLE
Bump dependencies to fix AppVeyor failures

### PR DESCRIPTION
**Pull request by sanmai**

### CODE REVIEW

**Comment by sanmai** [comment]
Now it is failing like so:
```
There was 1 failure:
1)          
         Infection\Tests\Console\ConsoleOutputTest::test_log_verbosity_deprecation_notice
Failed asserting that two     
         strings are identical.
--- Expected
+++ Actual
@@ @@
 '
- ! [NOTE] Numeric versions of log-verbosity have been 
         deprecated, please use, all to keep the same
- !        result
+ ! [NOTE] Numeric versions of log-verbosity    
         have been deprecated, please use, all to keep the same result
 
                                               
         '
C:\projects\workspace\tests\phpunit\Console\ConsoleOutputTest.php:82
FAILURES!                             
         Tests: 2, Assertions: 2, Failures: 1.                                                                          
                                                                                                                        
                                                                                                                        
```

**Comment by maks-rafalko** [comment]
Seems like after upgrading PHPParser, SA tools are not happy

**Comment by sanmai** [comment]
These are fixed, but now we have a different kind:
https://travis-ci.com/github/infection/infection/jobs/375603434#L413

Which looks like this:
https://github.com/symfony/symfony/issues/29341

**Comment by sanmai** [comment]
@maks-rafalko everything is green at last!

**Review by maks-rafalko — APPROVED** [review]
Cool!

**Pull request merged**
