### PR TITLE
Add console output break lines

### PR DESCRIPTION
**Pull request by kpn13**
This PR:

Fixes https://github.com/infection/infection/issues/798

Just add some new blank lines for the console output.

### CODE REVIEW

**Comment by sanmai** [comment]
[Looking at the Travis' build log... ](https://travis-ci.org/infection/infection/jobs/592225356#L722-L725)We now have an extra new line:
```
Processing source code files: 3


Creating mutated files and processes: 22
```
#798 might not be as easy as it looks.

**Comment by kpn13** [comment]
I think its better now. Should I rebase my branch ?

**Comment by maks-rafalko** [comment]
Since this is a bugfix, could you please target to `0.14` so we can release it as `0.14.2`?

**Comment by maks-rafalko** [comment]
Thank you @kpn13

**Pull request merged**
