### PR TITLE
Fix the order in which the infection configuration files are loaded

### PR DESCRIPTION
**Pull request by theofidry**
The expected order is:

- custom file if specified
- `infection.json` file if available
- `infection.json.dist` file

### CODE REVIEW

**Comment by maks-rafalko** [comment]
I guess this is BC break. Nothing bad here as we are on 0.x, but let's mark such issues so that we can list it on the blog post for 0.16 version / changelog

**Comment by theofidry** [comment]
Will check it out locally tonight

**Comment by theofidry** [comment]
Fair

**Comment by sanmai** [comment]
This isn’t a BC break, it’s a bug fix. Hard to BC break something that wasn’t working.

**Comment by maks-rafalko** [comment]
Why so? If you had 2 files (with and without `.dist`) and they had different content, they will be swapped right now, no?

**Comment by sanmai** [comment]
If you had `infection.json` before together with `infection.json.dist` the first was never ever considered.

**Comment by maks-rafalko** [comment]
> If you had `infection.json` before together with `infection.json.dist` the first was never ever considered.

right, and now (after this PR) it will be considered.

**Comment by sanmai** [comment]
Right, means I'm wrong that this isn't a BC break. It is both bug fix and BC break.

**Comment by maks-rafalko** [comment]
Exactly. Thanks ;)

**Pull request merged**
