### PR TITLE
Upgrade Infection to minimum PHP 8.0 using Rector

### PR DESCRIPTION
**Pull request by maks-rafalko**
Closes https://github.com/infection/infection/issues/1573

PHP 7.4 is no longer maintained. 

Used versions of Infection:

image

PHP 8 is used by the same number of users (approximately).

We released 0.26.0 with PHP 7.4 support and continue fix bugs for 0.26 branch. New releases will be for PHP 8.0 only.

Also, most of the boilerplate code, related to properties initialization, has been removed

image

### CODE REVIEW

**Comment by maks-rafalko** [comment]
should I wait for your review @sanmai?

**Review by sanmai — APPROVED** [review]
Let's go!

**Comment by maks-rafalko** [comment]
Thank you, @sanmai

**Comment by theofidry** [comment]
Sweet. I guess I'll bump PHP-Scoper & Box to PHP8 too then :D

**Pull request merged**
