### PR TITLE
Increase verbosity for Travis CI builds

### PR DESCRIPTION
**Pull request by sanmai**
This PR:

- [ ] Fixes CI build for PHP 7.4 + xdebug, hopefully

### CODE REVIEW

**Comment by maks-rafalko** [comment]
I would say this is quite a dangerous change for us.

I'm thinking about the cases like in this PR https://github.com/infection/infection/pull/1141 we got exactly "initial tests failed" error while I mistakenly thought that the issue is in the other place

Is it only for 0.16? We will merge 0.16. then back to master after release

**Comment by sanmai** [comment]
I rolled it back. In the end we only add `--skip-initial-tests` because apparently tests we causing Travis to timeout the build.

**Comment by maks-rafalko** [comment]
> because apparently tests we causing Travis to timeout the build.

is it because of the process does not output anything for a long time?

**Comment by sanmai** [comment]
It might be it, as we're running it with `--no-progress`. Yet it only failed for PHP 7.4 + xdebug for some unknown reason. I think `--skip-initial-tests` here offers a good opportunity to speed up our own builds.

**Pull request merged**
