### PR TITLE
Add PHP 7.4 to Travis CI

### LINKED ISSUE #774: Fix build for PHP 7.4 before November, 28
Fix Travis build for PHP 7.4 before the stable release

/remind @infection/core on November, 1

### PR DESCRIPTION
**Pull request by sanmai**
- Add a testing stage for PHP 7.4 + xdebug
- Require build passing for 7.4

This PR:
- [x] Hopefully does something about #774

### CODE REVIEW

**Comment by sanmai** [comment]
There's a hiccup [with Codeception something](https://travis-ci.org/infection/infection/jobs/620620519#L371), @maks-rafalko can you have a look?

**Comment by maks-rafalko** [comment]
> requires ext-zip * -> the requested PHP extension zip is missing from your system.

strange.. Ok, I will have a look but in the evening. Seem like `ext-zip` is not installed for PHP 7.4 ....

**Comment by sanmai** [comment]
It seems like [there's a reason to it](https://bugs.php.net/bug.php?id=78026). Shall we skip this test under PHP 7.4 for time being?

**Comment by maks-rafalko** [comment]
Many people from major repositories are experiencing the very same issue, as well as issues with other extensions:

* https://travis-ci.community/t/some-extensions-are-missing-in-php-7-4-0-zip-gmp-sodium/6320/12
* https://travis-ci.community/t/php-7-4-release/6197/10

So yeah, probably we just need to skip it for now and move forward.

**Comment by maks-rafalko** [comment]
Now Unit Tests work as expected for PHP 7.4 with XDebug.

There is [an issue with Box](https://travis-ci.org/infection/infection/jobs/623022804#L481): @theofidry you might be interested in this

> The configuration file failed validation: include(): _HumbugBox3ab8cff0fda0\Opis\Closure\ClosureStream::stream_set_option is not implemented!

**Comment by theofidry** [comment]
Box is not compatible with 7.4 yet: https://github.com/humbug/php-scoper/issues/357

**Comment by sanmai** [comment]
[leanphp/phpspec-code-coverage](https://github.com/leanphp/phpspec-code-coverage) isn't compatible with PhpSpec 6 which is [required for PHP 7.4](https://travis-ci.com/sanmai/phpspec-code-coverage/jobs/286169967#L207). What do we do?

TBH this package looks pretty much abandoned. Not a single update since 2018.

**Comment by theofidry** [comment]
@sanmai hopefully we'll have an alternative to the XML coverage report as a tracer this year, at the very least for PhpSpec, so this package will no longer be necessary!

**Comment by maks-rafalko** [comment]
Also, I'm working on extracting PHPSpec to a separate package, so `infection/infection` won't have this failing e2e test here anymore. Let's wait when it's done (and keep an eye on https://github.com/leanphp/phpspec-code-coverage/pull/40)

**Comment by sanmai** [comment]
Since there's work ongoing with PHPSpec, may I propose we merge this subset of changes?

Builds are failing due to unrelated issues. This PR changes nothing in terms of actual functionality, so it shouldn't introduce any new faults.

**Comment by sanmai** [comment]
It isn't getting better. Can we fix this in another PR, what do you think?
https://travis-ci.org/infection/infection/jobs/649890785#L378-L387

**Comment by sanmai** [comment]
Alright fingers crossed it should be fixed.

**Comment by maks-rafalko** [comment]
thank you @sanmai

**Comment by sanmai** [comment]
Thank you @maks-rafalko

**Pull request merged**
