### PR TITLE
Fix symfony/console 3.2 compatibility

### PR DESCRIPTION
**Pull request by sidz**
This PR fixes https://github.com/infection/infection/issues/435

### CODE REVIEW

**Comment by BackEndTea** [comment]
How does this work when using the coverage option with symfony/console 3.2?

**Comment by sidz** [comment]
@BackEndTea I didn't investigate to much but the answer somewhere here: https://github.com/symfony/console/commit/0572b233ec2b40d3e51d9e4f021c0da7d9c2113d

**Comment by BackEndTea** [comment]
> Seems to be in line with upstream changes, although it is somewhat surprising BC break with unclear reasons.

Reading the comment i think it has something to do with behaviour that changed in php 7

**Comment by borNfreee** [comment]
Thank you @sidz

**Pull request merged**
