### PR TITLE
Upgrade ondram/ci-detector to latest version

### PR DESCRIPTION
**Pull request by gruberro**
This PR:

- [x] Upgrades an existing project dependency `ondram/ci-detector` to its latest major version
- [x] Covered by existing tests

This PR aims to upgrade `ondram/ci-detector` to its latest major version, to ensure `infection` can be easily used together with tools like `composer-unused` requiring the new/latest major version of `ondram/ci-detector`.

### CODE REVIEW

**Comment by maks-rafalko** [comment]
For reference: related to https://github.com/infection/infection/pull/1642

**Review by maks-rafalko — APPROVED** [review]
Thank you!

If you need a release, I will do it tomorrow ASAP

**Comment by gruberro** [comment]
> Thank you!
> 
> If you need a release, I will do it tomorrow ASAP

That would be awesome - thank you very much for the fast response!

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/releases/tag/0.26.5

Thank you for your contribution.

**Pull request merged**
