### PR TITLE
Enable Symfony 5 components

### PR DESCRIPTION
**Pull request by edorosh**
This PR:

- [x] Adds support of new Symfony 5 Components.  #SymfonyHackday
- Not covered by tests. Let's see what CI shows

There 2 classes using deprecated (and removed in Symfony5) feature like [`Process::inheritEnvironmentVariables()`](https://github.com/symfony/process/blob/master/CHANGELOG.md)

* Infection\Process\Builder\MutantProcessBuilder
* Infection\Process\Builder\InitialTestRunProcessBuilder

That could be tricky to get rid of and support earlier versions of `symfony/process`. Here is the [source code for 4.4](https://github.com/symfony/process/blob/4.4/Process.php#L1222)

### CODE REVIEW

**Comment by maks-rafalko** [comment]
Thanks for creating this PR @edorosh, nice to meet you here LOL ;)

> There 2 classes using deprecated (and removed in Symfony5) feature like Process::inheritEnvironmentVariables()

Just opened a PR to fix it https://github.com/infection/infection/pull/843

**Comment by maks-rafalko** [comment]
> That could be tricky to get rid of and support earlier versions of symfony/process

We are still supporting symfony `3.4.x` (LTS) versions of components, and to avoid BC breaks, can't remove this method call, so I just wrapped it with a check of version.

**Comment by edorosh** [comment]
@maks-rafalko thanks! I was trying to find any behavioural way to figure out if you need to call that deprecated method. I mean smth like `isEnvInheritable`. But it seems Symfony didn't implement any marker to check the interface.

**Comment by maks-rafalko** [comment]
Thank you @edorosh

**Pull request merged**
