### PR TITLE
Add a describe command

### PR DESCRIPTION
**Pull request by BackEndTea**
This allows users to get a quick idea of a mutator,
without having to leave the cli.

This PR:

- [x] Adds a describe command, which describes mutators
- [x] Covered by tests
- [x] Doc PR: https://github.com/infection/site/pull/204

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]

**Comment by maks-rafalko** [comment]
nice

this is where "remedies" would be very useful. Also, just an idea for the future, we should probably add a diff example to the description of the mutators, that can be syntax-highlighted in this command

current behavior:

```diff
bin/infection describe                                                                                                                                           ✔  3s  08:23:14 

 What mutator do you wish to describe?:
 > Plus

Mutator Category: orthogonalReplacement

Description:
Replaces an addition operator (`+`) with a subtraction operator (`-`).
```

possible behavior:

```diff
bin/infection describe                                                                                                                                           ✔  3s  08:23:14 

 What mutator do you wish to describe?:
 > Plus

Mutator Category: orthogonalReplacement

Description:
Replaces an addition operator (`+`) with a subtraction operator (`-`).

- $a = $b + $c;
+ $a = $b - $c;
```

**Comment by BackEndTea** [comment]
I've added the diff to the definition. (Only for the Plus mutator for now)

**Review by maks-rafalko — APPROVED** [review]
:ok_hand:

**Comment by maks-rafalko** [comment]
Thank you @BackEndTea

**Comment by BackEndTea** [comment]
Thanks @maks-rafalko !

**Comment by theofidry** [comment]
❤️

**Pull request merged**
