### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] normalizes `composer.json`

💁‍♂️ I ran

```
$ composer global require localheinz/composer-normalize
```

followed by

```
$ composer normalize
```

For reference, see https://github.com/localheinz/composer-normalize.

### CODE REVIEW

**Comment by sanmai** [comment]
Builds are failing with...

> The minimum required MSI percentage should be 90%, but actual is 79%.

Not sure how this change can be the reason.

**Comment by borNfreee** [comment]
could you please resolve conflict with `composer.lock`?

**Comment by borNfreee** [comment]
Thank you @localheinz

**Comment by localheinz** [comment]
Thank you, @borNfreee and @sanmai!

**Pull request merged**
