### PR TITLE
This should be ran when the normal mutation runs

### PR DESCRIPTION
**Pull request by BackEndTea**
This PR changes the mutator tests so the mutation happends at the right time.

### CODE REVIEW

**Comment by maks-rafalko** [comment]
What was the issue that this change fixes? Is it possible to cover it by test?

**Comment by BackEndTea** [comment]
It shouldn't be an issue, because this visitor uses leaveNode, while a lot of others use enterNode.

I ran into this while working on the reflection wrappers, so i decided to make a seperate PR for it.

**Comment by theofidry** [comment]
>I ran into this while working on the reflection wrappers, so i decided to make a seperate PR for it.

I mean the question here is why that change? We just see a `100` -> `10` but why is that?

**Comment by BackEndTea** [comment]
the 100 to 10 is the change of priority for the muation collector that is used by the tests. (The simple mutation collector).

In the current situation this visitor was actually the first to ran. The only reason this wasn't an issue, is that this visitor uses leaveNode, and the other ones use enterNode, causing them to still be executed earlier

**Pull request merged**
