### PR TITLE
Small code cleanup changes

### PR DESCRIPTION
**Pull request by Landerstraeten**

### CODE REVIEW

**Comment by Landerstraeten** [comment]
No clue why PHP7.2 build is failing

**Comment by Landerstraeten** [comment]
No clue why travis 7.2 build is failing

**Comment by borNfreee** [comment]
Hello, please see my comment in your first PR about PHP 7.1 https://github.com/infection/infection/pull/58#discussion_r150636026 and revert it.

Besides that, looks good to me.

**Comment by borNfreee** [comment]
Thank you @Landerstraeten

**Pull request merged**
