### PR TITLE
If PATH is not set, continue infection execution with fallback

### PR DESCRIPTION
**Pull request by borNfreee**
If PATH/Path is not set, fall back to `vendor/bin` in `ComposerExecutableFinder`
and continue Infection execution instead of displaying a weird error

Fixes https://github.com/infection/infection/issues/295

### CODE REVIEW

**Comment by BackEndTea** [comment]
Is there any way to mimic this behaviour (not having a path set). Because if so it might be nice to add a test for it.

**Comment by sanmai** [comment]
The only objection is hanging empty `Empty_Path/README.md`.

**Comment by borNfreee** [comment]
Unfortunately, on Travis, setting `PATH=` [breaks the build](https://travis-ci.org/infection/infection/jobs/370291735#L785). After setting empty value to `PATH`, Travis does not know any command (bash, which, php, etc.).

Tested on Travis VM (connected by ssh to the build):

```bash
cd tests/Fixtures/e2e/Empty_Path

PATH=  run_tests.bash

/usr/bin/env: bash: No such file or directory
```

then 

```bash
PATH= /bin/bash run_tests.bash

which: No such file or directory
/usr/bin/env: php: No such file or directory
```

I have no idea how to resolve this.

**Comment by borNfreee** [comment]
> what about https://github.com/infection/infection/blob/master/src/Finder/TestFrameworkFinder.php#L103 line?

at the moment of line 103, `PATH` will always have the value even if it was empty, because of https://github.com/infection/infection/blob/master/src/Finder/TestFrameworkFinder.php#L84 (`addVendorFolderToPath()`). So I see no way that this line can cause an issue.

**Comment by sanmai** [comment]
What about this:
```bash
phpdbg=$(phpdbg)
PATH= $phpdbg -qrr $INFECTION
```

**Comment by BackEndTea** [comment]
Could we have a bootstrap file which simply does a `putenv` of path.

**Comment by borNfreee** [comment]
@BackEndTea could you please explain it in more details ?

**Comment by borNfreee** [comment]
@BackEndTea it works!

**Pull request merged**
