### PR TITLE
Increase niceness for mutant processes

### PR DESCRIPTION
**Pull request by sanmai**
A runaway mutation (#1145) can cause a system resource exhaustion. Therefore, Infection may not be able to secure enough CPU cycles to stop this malignant mutation on time.

- We can work around this issue if we make Infection run with a higher priority by lowering priority of mutant processes. (Raising own priority usually is impossible, and not advisable in principle.)
- Downside of running anything with lower priority is that OS will not spin up CPU as much as it would for a higher- or normal-priority processes. Therefore Infection may run slower on energy-limited devices like laptops.
- This approach [works on Windows too](https://www.php.net/manual/en/function.proc-nice.php#refsect1-function.proc-nice-changelog).

This PR also add syntax validation, which we can keep if the above idea does not find approval.

### CODE REVIEW

**Comment by sanmai** [comment]
Thank you @theofidry

**Comment by maks-rafalko** [comment]
Could you please explain in different words how it was working before and what is changed with this function call? I don't think I understood the issue and solution, sorry

**Comment by sanmai** [comment]
After starting mutation processes Infection checks in a loop if they're out of time, with a slight delay. The problem is that this delay isn't guaranteed in non-RTOS. If the system is under a heavy load, it may take quite some time until Infection is given control back to stop these "timed out" processes. 

But if we lower priority for these processes, we can reasonably expect that the operating system will prioritize Infection main process over these rogue mutant processes. 

The quicker Infection can react to them, the less harm is done, and smoother things go.

**Comment by maks-rafalko** [comment]
Rocket since. Thank you @sanmai

**Pull request merged**
