### PR TITLE
Replace abandoned `webmozart/path-util` with `symfony/filesystem`

### PR DESCRIPTION
**Pull request by martinssipenko**
This PR:

Replaces abandoned `webmozart/path-util` with `symfony/filesystem`.

Fixes https://github.com/infection/infection/issues/1634

### CODE REVIEW

**Comment by martinssipenko** [comment]
I just noticed the conversation in #1634 about dropping Symfony below `5.4`. Question I have is why do you need to keep those old Symfony versions?

**Review by maks-rafalko — APPROVED** [review]
I think we don't need it.

image

All the versions below 5.4 EOLd, so personally I'm ok with the current state of this PR.

Users with older SF versions will use Infection <= 0.26.10

**Comment by martinssipenko** [comment]
@maks-rafalko dunno whether 4.4 works on PHP 8.0, which is required for Infection. Will you merge the PR then? I later can follow up with another one to remove < 5.4 altogether.

**Comment by maks-rafalko** [comment]
> dunno whether 4.4 works on PHP 8.0

according to symfony repostiories and GH Actions, it works even on 8.1

> Will you merge the PR then?

yes, right now

> I later can follow up with another one to remove < 5.4 altogether.

do you think it's needed? for what reason?

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/releases/tag/0.26.11

**Pull request merged**
