### PR TITLE
Move ProtectedVisibility Mutators to dedicated file

### PR DESCRIPTION
**Pull request by deleugpn**
Carrying on the work started on #512

### CODE REVIEW

**Comment by sanmai** [comment]
This all can be even better if a test would scan for files in an automatically detected directory, then run tests against those files. Adding a news test will be a matter of adding a file or two. And if it could see that there is only `m0.php` file, of if there's a pair of `m0.php` `m1.php` then it could also automatically check for correct mutations. What do you think?

**Comment by borNfreee** [comment]
> And if it could see that there is only `m0.php` file, of if there's a pair of `m0.php` `m1.php` then it could also automatically check for correct mutations.

I think this will not be clear for new contributors, and even for us in a month or two. As for me - it's better to leave as is - explicitly and without magic.

**Comment by deleugpn** [comment]
I also thought about how to make it less brittle, but as borNfreee mentioned it would be 'too magical' at this point. I was thinking about just keeping it like this for now and as we get more into  this routine, perhaps another refactoring could come in and improve the way of writing these tests even more.

**Comment by borNfreee** [comment]
Closing as the very similar PR was also closed https://github.com/infection/infection/pull/512

Feel free to reopen if you find some time and still thinks it's needed.

**Pull request closed without merging**
