### PR TITLE
Tweak PhpProcess

### PR DESCRIPTION
**Pull request by theofidry**
- Move PhpProcess from Infection\Console\Util to Infection\Process
- Rename PhpProcess to XdebugProcess

### CODE REVIEW

**Comment by theofidry** [comment]
Because it's about manipulating XdebugHandler

**Comment by sanmai** [comment]
Well, at what point it does anything with XdebugHandler? True, it does use a class from XdebugHandler to manipulate environment variables, but they may or may not change a thing in terms of Xdebug usage. Even you mention in the comment that "for example" it'd modify environment to reinstate Xdebug if it was.

If it would be 100% launching a process with Xdebug, I would understand this name change. But it isn't.

**Comment by theofidry** [comment]
Then `XdebugHandlerProcess`? `PhpProcess` does not makes sense to me: it's not more "php" than the parent `Process` and does not manipulate PHP directly either

**Comment by maks-rafalko** [comment]
What about `OriginalPhpProcess` / `OriginalPhpConfigProcess` or something like that?

**Pull request merged**
