### PR TITLE
Enhancement: Implement UnwrapArrayReplace mutator

### PR DESCRIPTION
**Pull request by localheinz**
This PR

- [x] Adds new feature `UnwrapArrayReplace` mutator
- [x] Covered by tests
- [x] Doc PR: https://github.com/infection/site/pull/78

Related to #514.

💁‍♂️ Follows the example in https://github.com/infection/infection/pull/513.

### CODE REVIEW

**Comment by localheinz** [comment]
@borNfreee 

I could imagine that this mutator could create as many mutations as arguments are passed to `array_replace()`, what do you think?

**Comment by borNfreee** [comment]
Do you mean this?

```diff
- $d = array_replace(['a'], ['b'], ['c']);
+ $d = ['a'];
+ $d = ['b'];
+ $d = ['c'];
```
?

I didn't do any analyzing but this sounds good to me.

**Comment by localheinz** [comment]
@borNfreee 

Exactly!

**Comment by sanmai** [comment]
So there go mutators for `array_merge()`, `array_diff()`, `array_replace_recursive()`,`array_intersect()`, `array_intersect_assoc()`, `array_uintersect()`... Many of them. I had these on my mind for some time, but implementing them now is like putting #494 back even further. And this important PR already needs some work to cover these new mutators.

**Comment by localheinz** [comment]
@sanmai 

> Seems doable, what do you think?

Absolutely! For now I implemented it for the `UnwrapArrayReplace` mutator specifically, but I don't mind adjusting.

**Comment by localheinz** [comment]
@borNfreee @sanmai 

What do you think about aaa1f75?

**Comment by sanmai** [comment]
There's something PHPStan did not like.

**Comment by borNfreee** [comment]
Thank you @localheinz

**Comment by localheinz** [comment]
Thank you, @borNfreee and @sanmai!

**Pull request merged**
