### PR TITLE
Add `mbstring` in the list of required php extensions

### PR DESCRIPTION
**Pull request by khalyomede**
Fixes https://github.com/infection/infection/issues/1696

This PR adds the `ext-mbstring` extension as a requirements in `composer.json`, to help prevent further issues in case this extension is not found during the initialization step.

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]
Thank you.

Please run `composer update --lock` to fix the build and it will be good to merge

**Comment by khalyomede** [comment]
Thank you for the guidance I just locked dependencies (27f5c71)

**Comment by maks-rafalko** [comment]
Could I ask you rebase? Seems like anoth PR merged to master conflicts now with the changes. I will enable automerge, thank you.

**Comment by maks-rafalko** [comment]
Seems like many of the libs have been accidently upgraded, and now PHPStan fails. Please revert `composer.lock` file and just do `composer update --lock`

**Comment by maks-rafalko** [comment]
Replaced by https://github.com/infection/infection/pull/1709

Thank you @khalyomede

**Pull request closed without merging**
