### PR TITLE
Account for statements spanning multiple lines

### PR DESCRIPTION
**Pull request by sanmai**
- [x] MutationsCollectorVisitor now accounts for statements spanning multiple lines
- [x] Covered by tests

Fixes https://github.com/infection/infection/issues/366

### CODE REVIEW

**Comment by BackEndTea** [comment]
I'm not 100% sure, but i thought that function signatures were 100% covered, e.g. for the following signature, if it is called, all lines are considered covered

```php
public function foo(
    $a,
    $b,
    $c,
    $d
    ) {
}
```

**Comment by sanmai** [comment]
I'm not sure about that too, but even if that is so, it shouldn't matter. 

Anyway, I'm going to be adding tests, so I'd test for this case too.

**Comment by sanmai** [comment]
@BackEndTea you were right: there's no need to check for each line on function signatures

**Comment by BackEndTea** [comment]
Won't we run into issues on this line
https://github.com/infection/infection/blob/3518545a6bab661f33a47750809dfd8d487ed7b4/src/TestFramework/Coverage/CodeCoverageData.php#L124

Because there it will still look at the original line, rather than the one we found tests on.

**Comment by sanmai** [comment]
Considering it reports all mutants properly caught, and no uncovered mutants... OK, let me try to think of some extra test cases which may see Infection err on that line.

**Comment by sanmai** [comment]
Actually that line is important. If Infection only looks for tests that cover only the very first line of our mutation, it may naturally miss other tests that may actually also cover this mutation, this all leading to false positives. 

Yet we have to way to verify that Infection has found all tests covering specific mutation since we're not logging the number of tests found. Neither were bugs reported in this regard.

**Comment by borNfreee** [comment]
I've changed base branch from `master` to `0.9`. Details are in the Slack

**Comment by borNfreee** [comment]
Thank you @sanmai

**Pull request merged**
