### PR TITLE
Test that .travis.yml is valid

### PR DESCRIPTION
**Pull request by sanmai**
Since Travis CI [is known to silently fail if .travis.yml isn't valid](https://github.com/infection/infection/pull/249#issuecomment-375268364), we have a chance to check for that during routine testing, and at AppVeyor during normal CI.

### CODE REVIEW

**Comment by theofidry** [comment]
I've just changed the Travis config from `Build only if .travis.yml is present`: `Off` => `On`. It doesn't look like that would fix it but that's the only parameter I see in the config that can remotely match what we are looking for. Could you try to see if that changes anything?

**Comment by sanmai** [comment]
So Travis won't even build if .travis.yml is invalid. But good news is new test got it right and failed builds on AppVeyor.

**Comment by sanmai** [comment]
Good idea. Done.

**Comment by borNfreee** [comment]
Thank you @sanmai

**Pull request merged**
