### PR TITLE
Fix spelling in console output

### PR DESCRIPTION
**Pull request by MidnightDesign**
Fixes the spelling in the "consider increasing the required..." message

### CODE REVIEW

**Review by sanmai — APPROVED** [review]

**Review by maks-rafalko — APPROVED** [review]
Thank you @MidnightDesign

**Comment by maks-rafalko** [comment]
could you please look into failed builds?

**Comment by MidnightDesign** [comment]
I don't get it. It either breaks in AppVeyor or in GH Actions. Do they use different line lengths or something?

**Comment by sanmai** [comment]
It breaks on Travis CI too. This is definitely has something to do with terminal width.

**Comment by sanmai** [comment]
I get the same error when I set COLUMNS to 99.

**Review by maks-rafalko — APPROVED** [review]
Thank you all

**Comment by MidnightDesign** [comment]
@sanmai Thank you so much for fixing my PR!

**Comment by sanmai** [comment]
No problem at all! I wish we didn't have to deal with this `PHP_EOL` BS, but here we are.

**Pull request merged**
