### PR TITLE
Add autoreview workflow

### PR DESCRIPTION
**Pull request by sanmai**
This PR:

- [x] Adds GitHub Workflow with a set of autoreview tests and checks

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]
Should we remove it from TravisCI then

**Comment by sanmai** [comment]
That's the idea, but that needs slightly more consideration. 

Scrutinizer is getting annoying. Now it uses PHP 7.3, and then it uses PHP 7.4. Can we get it sorted? I don't think I have the knobs to do it.

**Comment by maks-rafalko** [comment]
> Scrutinizer is getting annoying

I have to admit I didn't use Scrutinizer report for ages (years). It doesn't prevent from merging and we don't use any of the complaints from it (I suppose)

Do we really need it? :|

**Comment by sanmai** [comment]
TBH I hardly remember any actionable feedback from it... Remove it then?

**Comment by maks-rafalko** [comment]
ok, removed

**Pull request merged**
