### PR TITLE
Replace custom XdebugHandler by composer/xdebug-handler package

### PR DESCRIPTION
**Pull request by sidz**
This PR is replacing our custom XdebugHandler by `composer/xdebug-handler` package

### CODE REVIEW

**Comment by BackEndTea** [comment]
Could you remove the exclude for the class from the infection config file

**Comment by sidz** [comment]
@borNfreee there is an issue with 4.0 but I'm not sure why it happened

**Comment by sidz** [comment]
@BackEndTea done.

**Comment by BackEndTea** [comment]
Testing against Symfony 4 locally still gives errors.

**Comment by sidz** [comment]
@BackEndTea could you please give a bit more details. which kind of issues did you get?

**Comment by BackEndTea** [comment]
Using a var_dump to get the output of the phpunit process it shows this:

```
PHPUnit 6.5.7 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

......................................SS..S........S.......S...  63 / 439 ( 14%)
............................................................... 126 / 439 ( 28%)
............................................................... 189 / 439 ( 43%)
............................................................... 252 / 439 ( 57%)
............................................................... 315 / 439 ( 71%)
............................................................... 378 / 439 ( 86%)
.............................................................   439 / 439 (100%)

Time: 796 ms, Memory: 68.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 439, Assertions: 832, Skipped: 5.
```

> Error:         No code coverage driver is available

Being the important part.

For some reason there is no issue with lower symfony versions, but removing the `platform` constraints, and running composer update causes xdebug to not be loaded.

**Comment by BackEndTea** [comment]
From what i can tell, it starts as normal, and then restarts, with xdebug disabled.

**Comment by BackEndTea** [comment]
I'm 99% sure it has something to do with 
`$process->inheritEnvironmentVariables();` in our ProcessBuilder. 

We only want to run that if we are skipping coverage, or runnign with phpdbg, but in 4.0 this is default behaviour, and can't be changed.

**Comment by sidz** [comment]
@BackEndTea I can't replicate your issue also travis didn't show any issues. Do you use macOS?

**Comment by BackEndTea** [comment]
I ran it on fedora.

If you remove the platform part of the json config, and run composer update, you get the errors, when runing infection without providing coverage, or having it in cahce somewhere

**Comment by sidz** [comment]
I've ran it in the same way like travis do:
```
    "config": {
        "platform": {

        },
        "sort-packages": true
    },
    "conflict": {
        "symfony/process": "3.4.2"
    },
    "require": {
        "php": "^7.0",
        "composer/xdebug-handler": "^1.0",
        "nikic/php-parser": "^4.0",
        "ocramius/package-versions": "^1.2",
        "padraic/phar-updater": "^1.0.4",
        "pimple/pimple": "^3.2",
        "sebastian/diff": "^1.4 || ^2.0 || ^3.0",
        "symfony/console": "^4.0",
        "symfony/filesystem": "^4.0",
        "symfony/finder": "^4.0",
        "symfony/process": "^4.0",
        "symfony/yaml": "^4.0"
    },
```

p.s. I'll try your steps

**Comment by BackEndTea** [comment]
assuming you are runnign default infection.json.dist, could you try something like `rm -rf /tmp/infection`

**Comment by BackEndTea** [comment]
Running it with #275 should also display that we are using deprecated functionality.

**Comment by sidz** [comment]
> assuming you are runnign default infection.json.dist, could you try something like rm -rf /tmp/infection

Doesn't help - works as expected.

> Running it with #275 should also display that we are using deprecated functionality.

4.0 can't trigger this error as there is no `@trigger_error` call anymore. Also it wouldn't break Infection as there is `@`.
3.4: https://github.com/symfony/process/blob/v3.4.3/Process.php#L310 (our current version) and infection works fine with it at least 3 months.
4.0: https://github.com/symfony/process/blob/v4.0.6/Process.php#L1134 there is no trigger_error anymore and also `inheritEnvironmentVariables` method is doing nothing so it shouldn't break anything.

**Comment by theofidry** [comment]
@sidz I feel like this requires proper review. I'll try to commit to this next week I can't today neither this week-end so if that's alright with you I wish you guys could wait on me for that one 🙏

**Comment by johnstevenson** [comment]
@BackEndTea I think this is down to me in `composer/xdebug-handler`, when we restore the environment in the restarted process. I `putenv` _PHP_INI_SCAN_DIR_ to its original state, but this is not reflected in `$_SERVER` which is used by Symfony to set the default environment for the new process.

Could you please confirm if you are using more than one ini file (ie. scanned inis), by running `php --ini`.

**Comment by BackEndTea** [comment]
@johnstevenson I simply ran it with the following Dockerfile
```Dockerfile
FROM php:7.2-cli

RUN pecl install xdebug && docker-php-ext-enable xdebug
```

**Comment by johnstevenson** [comment]
@BackEndTea Thanks, but just to be sure the `php --ini` output would be useful.
```
docker run -it --rm  image-name /bin/bash
```

**Comment by theofidry** [comment]
Provided everything works (I can't test it atm) 👍

**Comment by BackEndTea** [comment]
@johnstevenson 
```
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
```
was the output

**Comment by BackEndTea** [comment]
With a 
```php
var_dump(file_get_contents(php_ini_loaded_file ()));
```
inside of the symfony process, i get the following output for symfony 3.4 & 4:
```
extension=sodium.so

;zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so

allow_url_fopen=1
allow_url_include=0
arg_separator.input="&"
arg_separator.output="&"
assert.active=1
assert.bail=0
assert.exception=0
assert.quiet_eval=0
assert.warning=1
auto_detect_line_endings=0
auto_globals_jit=1
cli.pager=
cli.prompt="\b \> "
curl.cainfo=
date.default_latitude="31.7667"
date.default_longitude="35.2333"
date.sunrise_zenith="90.583333"
date.sunset_zenith="90.583333"
date.timezone=
default_charset="UTF-8"
default_mimetype="text/html"
default_socket_timeout=60
disable_classes=
disable_functions=
display_errors=1
display_startup_errors=0
docref_ext=
docref_root=
enable_dl=1
enable_post_data_reading=1
expose_php=1
extension_dir="/usr/local/lib/php/extensions/no-debug-non-zts-20170718"
file_uploads=1
filter.default="unsafe_raw"
hard_timeout=2
highlight.comment="#FF8000"
highlight.default="#0000BB"
highlight.html="#000000"
highlight.keyword="#007700"
highlight.string="#DD0000"
html_errors=0
iconv.input_encoding=
iconv.internal_encoding=
iconv.output_encoding=
ignore_repeated_errors=0
ignore_repeated_source=0
ignore_user_abort=0
implicit_flush=1
include_path=".:/usr/local/lib/php"
log_errors=0
log_errors_max_len=1024
mail.add_x_header=0
max_execution_time=0
max_file_uploads=20
max_input_nesting_level=64
max_input_time="-1"
max_input_vars=1000
mbstring.encoding_translation=0
mbstring.func_overload=0
mbstring.http_output_conv_mimetypes="^(text/|application/xhtml\+xml)"
mbstring.language=neutral
mbstring.strict_detection=0
memory_limit=128M
mysqlnd.collect_memory_statistics=0
mysqlnd.collect_statistics=1
mysqlnd.fetch_data_copy=0
mysqlnd.log_mask=0
mysqlnd.mempool_default_size=16000
mysqlnd.net_cmd_buffer_size=4096
mysqlnd.net_read_buffer_size=32768
mysqlnd.net_read_timeout=86400
output_buffering=0
pcre.backtrack_limit=1000000
pcre.jit=1
pcre.recursion_limit=100000
phar.cache_list=
phar.readonly=1
phar.require_hash=1
post_max_size=8M
precision=14
realpath_cache_size=4096K
realpath_cache_ttl=120
register_argc_argv=1
report_memleaks=1
report_zend_debug=0
sendmail_path=" -t -i "
serialize_precision="-1"
session.auto_start=0
session.cache_expire=180
session.cache_limiter=nocache
session.cookie_domain=
session.cookie_httponly=0
session.cookie_lifetime=0
session.cookie_path="/"
session.cookie_secure=0
session.gc_divisor=100
session.gc_maxlifetime=1440
session.gc_probability=1
session.lazy_write=1
session.name=PHPSESSID
session.referer_check=
session.save_handler=files
session.save_path=
session.serialize_handler=php
session.sid_bits_per_character=4
session.sid_length=32
session.trans_sid_hosts=
session.trans_sid_tags="a=href,area=href,frame=src,form="
session.upload_progress.cleanup=1
session.upload_progress.enabled=1
session.upload_progress.freq="1%"
session.upload_progress.min_freq=1
session.upload_progress.name="PHP_SESSION_UPLOAD_PROGRESS"
session.upload_progress.prefix="upload_progress_"
session.use_cookies=1
session.use_only_cookies=1
session.use_strict_mode=0
session.use_trans_sid=0
short_open_tag=1
SMTP=localhost
smtp_port=25
track_errors=0
upload_max_filesize=2M
url_rewriter.hosts=
url_rewriter.tags="form="
user_ini.cache_ttl=300
user_ini.filename=".user.ini"
variables_order=EGPCS
xmlrpc_error_number=0
xmlrpc_errors=0
zend.assertions=1
zend.detect_unicode=1
zend.enable_gc=1
zend.multibyte=0
zend.signal_check=0
zlib.output_compression=0
zlib.output_compression_level="-1"
zlib.output_handler=
opcache.enable_cli=0
```

**Comment by sidz** [comment]
@johnstevenson great thx. Any chance that you will trigger 1.0.1 or so?

**Comment by sanmai** [comment]
I believe this should go after/above #285 because #285 does *very* elaborate things with Infection. If there's an issue, tests from #285 will show it.

**Comment by johnstevenson** [comment]
@sidz See https://github.com/composer/xdebug-handler/releases/tag/1.1.0 which contains all the stuff I mentioned. The readme explains most things, but shout if you have any questions.

I've also released a tiny helper package (https://packagist.org/packages/johnstevenson/xdebug-handler-opts) which wraps `XdebugHandler::getRestartSettings()` to provides PHP command-line options and set up the environment. If it's useful, I may incorporate it into xdebug-handler. For example:

```php
use JohnStevenson\XdebugHandler\PhpOpts;

$opts = new PhpOpts;
...

// call phpunit (with xdebug loaded)
$options =  $opts->getOptions(PhpOpts::RS_IGNORE);

// call infection sub-processes (without xdebug)
$options = $opts->getOptions(PhpOpts::RS_SAFE);

// add the PHP options to the command-line
```
You would need to change the way you currently build your command-line, unfortunately. Although you may have to do this anyway because the later symfony/process code does not escape it if you provide a string (you need to provide an array).

**Comment by sanmai** [comment]
I get all kind of different errors:

```
git fetch upstream pull/263/head:pr-263
git checkout pr-263
git rebase master
composer install
./tests/e2e_tests
```

E.g.
```
Fatal error: Uncaught Error: Call to undefined function Composer\XdebugHandler\ctype_alnum() in $dataRec->vendor/composer/xdebug-handler/src/XdebugHandler.php on line 437

Error: Call to undefined function Composer\XdebugHandler\ctype_alnum() in $dataRec->vendor/composer/xdebug-handler/src/XdebugHandler.php on line 437

Call Stack:
    0.0001     398784   1. {main}() $dataRec->bin/infection:0
    0.0066    1302056   2. Infection\Console\Application->run() $dataRec->bin/infection:13
    0.0142    1897320   3. Composer\XdebugHandler\XdebugHandler->check() $dataRec->src/Console/Application.php:87
    0.0144    1915896   4. Composer\XdebugHandler\XdebugHandler->prepareRestart() $dataRec->vendor/composer/xdebug-handler/src/XdebugHandler.php:115
    0.0144    1916368   5. Composer\XdebugHandler\XdebugHandler->writeTmpIni() $dataRec->vendor/composer/xdebug-handler/src/XdebugHandler.php:287
    0.0146    1929688   6. Composer\XdebugHandler\XdebugHandler->mergeLoadedConfig() $dataRec->vendor/composer/xdebug-handler/src/XdebugHandler.php:330
```

**Comment by sidz** [comment]
@sanmai fix for `ctype` has been merged into xdebug-handler repo

**Comment by sanmai** [comment]
So I rebased again against master:
```bash
git rebase master -Xtheirs
```
And now I'm getting:
```
Provide_Existing_Coverage/
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 
Running initial test suite...

PHPUnit version: 6.5.8


 [ERROR] Project tests must be in a passing state before running Infection.                                             
                                                                                                                        
         Phpunit reported an exit code of 143.                                                                          
                                                                                                                        
         Refer to the phpunit's output below:                                                                           
                                                                                                                        
         STDERR:                                                                                                        
                                                                                                                        
         Cannot load Zend OPcache - it was already loaded                                                               
```

I believe this is the same problem #310 should solve. BTW #310 makes PhpExecutableFinder even more redundant, so all in all it is best to wait until #310 merges, then fixing this PR will be a piece of cake. Or making it from scratch, if that matters.

**Comment by sidz** [comment]
don't like 310 really. this vanillaPhpProcess is a mess.

**Comment by sanmai** [comment]
Well, how do you want it to be?

**Comment by sidz** [comment]
@sanmai I've rebased it with the latest master and there is no any issues. Travis is green.

p.s. Also current master failed on my local machine:
```
1) Infection\Tests\Console\E2ETest::test_it_runs_an_e2e_test_with_success with data set #3 ('Trait_Coverage', Symfony\Component\Finder\SplFileInfo Object (...))
/var/www/infection/tests/Fixtures/e2e/Trait_Coverage/expected-output.txt is not same as infection-log.txt (if that is OK, run GOLDEN=1 vendor/bin/phpunit)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Mutator: PublicVisibility\n
-Line 10\n
-\n
-Mutator: PublicVisibility\n
@@ @@
 Line 12\n
+\n
+Mutator: PublicVisibility\n
+Line 10\n
 \n
 Errors mutants:\n
 ===============\n
 \n
 \n
 Escaped mutants:\n
 ================\n
 \n
 \n
 Timed Out mutants:\n
 ==================\n
 \n
 \n
 Not Covered mutants:\n
 ====================\n
 \n
 \n
 Mutator: DecrementInteger\n
 Line 18\n
 \n
 Mutator: OneZeroInteger\n
 Line 18\n
 '

/var/www/infection/tests/Console/E2ETest.php:147
/var/www/infection/tests/Console/E2ETest.php:95

```

**Comment by sanmai** [comment]
@sidz that's great! could you try with extra test cases I added in #310?

Specifically you will need to update these two files:
https://github.com/sanmai/infection/blob/f4d3e8a4a927874bd27e596fc34b299491b2abc7/tests/Fixtures/e2e/Exec_Path/run_tests.bash
https://github.com/sanmai/infection/blob/f4d3e8a4a927874bd27e596fc34b299491b2abc7/tests/Fixtures/e2e/Exec_Path/bin/test.bash

Also, could you verify that initial test run does not runs with xdebug enabled if coverage provided?

**Comment by sanmai** [comment]
These are out of expected order:
``` 
Mutator: PublicVisibility\n
-Line 10\n
-\n
-Mutator: PublicVisibility\n
@@ @@
 Line 12\n
+\n
+Mutator: PublicVisibility\n
+Line 10\n
 \n
```

What locale do you use on your machine?

**Comment by sidz** [comment]
```
sid@sid:/var/www/infection$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by sidz** [comment]
> that's great! could you try with extra test cases I added in #310?

> Specifically you will need to update these two files:
tests/Fixtures/e2e/Exec_Path/run_tests.bash
tests/Fixtures/e2e/Exec_Path/bin/test.bash

everything fine. (I've modified these 2 files only)

> Also, could you verify that initial test run does not runs with xdebug enabled if coverage is provided? On master it runs with xdebug enabled at all times.
why do you think that 'Initial test runner' runs with xdebug?

my test env:
- xdebug enabled;
- run infection with `--coverage` provided;
- did dump on `$process->getCommandLine()` and got full command line string;
- opened php.ini which XdebugHandler did for us;
- found: 
```
;zend_extension=xdebug.so

xdebug.remote_host=127.0.0.1
xdebug.remote_enable=1
;xdebug.idekey="PHPSTORM"
```
So the child process should be executed without xdebug.

**Comment by sanmai** [comment]
Still failing test for issue #306, unfortunately.

**Comment by sidz** [comment]
I vote to merge this PR first and then I'll take a look what is going on with your issue as I'm still not sure what are you trying to solve

**Comment by sanmai** [comment]
I'm trying to fix `make test` - it isn't working now.

No need to hurry, there's #310 which fixes #306. This PR can make thins worse.

**Comment by sidz** [comment]
first of all seems like your issue is specific only for the docker environment as we don't see it before. With your current description in the https://github.com/infection/infection/issues/306 we should have the same issue everywhere it shouldn't happen on docker only.

Also as we discussed before `ConfigBuilder` and others are deprecated and we don't won't to support it anymore so IMO https://github.com/infection/infection/pull/310 shouldn't go before this PR.

**Comment by sanmai** [comment]
No questions about #310 - it is way better to use composer-supported XdebugHandler than our solution whatever it may be. 

The issue #306 is a symptom of larger problem: environment pollution. When we're using our own XdebugHandler, we're in a total control of the environment. When we're using composer-supported XdebugHandler, we're at their mercy. This is not a good idea generally for a project, that heavy relies on sub-processes.

**Comment by johnstevenson** [comment]
If you use the new features of xdebug-handler, then the environment is handled for you. I've designed it so that you can happily chain as many sub-processes together as you want and, provided that you know what the sub-process does (in terms of using ini files or creating its own sub-process) then there should not be any problems.

If the sub-process implements xdebug-handler itself (like infection does, but it could be any other app) then this works out of the box without you having to worry about anything.

**Comment by sanmai** [comment]
> If the sub-process implements xdebug-handler itself then this works out of the box

That's certainly not phpunit nor phpspec Infection usually need to run.

@johnstevenson any ideas on why we could have #306 happening?

**Comment by johnstevenson** [comment]
@sanmai https://github.com/infection/infection/issues/306 happens because `PHP_INI_SCAN_DIR` isn't restored to its original state in the restart.

> That's certainly not phpunit nor phpspec Infection usually needs to run.

Take a look at the readme here: https://github.com/composer/xdebug-handler

You can run phpunit with xdebug loaded (for code coverage) no problem at all.

Running it without xdebug (ie using the same settings that were used in the restart) may cause problems if scanned inis were used AND phpunit runs the tests in a sub-process. However, there are ways around this as well.

Please ask if you need more information.

**Comment by sanmai** [comment]
@johnstevenson thank you for you time to answer my question. I took a break with my previous comment precisely to take a closer look at the readme. That didn't work.

Is it correct to say that all our sub-process are going to run with xdebug loaded, unless we somehow manage to inject xdebug-handler into them?

**Comment by sanmai** [comment]
@sidz it appears we're still using older version of xdebug-handler

```
$ composer show composer/xdebug-handler | grep ver
versions : * 1.0.0
```

**Comment by sidz** [comment]
@sanmai yup I know. don't have enough time. I'll update it today

**Comment by johnstevenson** [comment]
@sanmai 

> Is it correct to say that all our sub-process are going to run with xdebug loaded

If you are in a restarted process, then yes, unless that sub-process implements xdebug-handler. To quote:

_Calling a PHP process from a restarted process will result in xdebug being loaded in that process, or another restart if xdebug-handler is implemented._

> ... unless we somehow manage to inject xdebug-handler into them?

There is no injecting. You just make use of the restart settings.

**Comment by theofidry** [comment]
@sanmai I had something similar in https://github.com/amphp/parallel/pull/47#issuecomment-383867241, we can re-use the config passed in this scenario to avoid another restart

**Comment by sanmai** [comment]
@theofidry indeed we can, but only one level deep. E.g. if a PHP program starts a PHP program, it will run with xdebug and all things. Architecture proposed by this PR won't let us force our php.ini on all subprocesses.

**Comment by sidz** [comment]
@sanmai travis caught the issue which I described above https://travis-ci.org/infection/infection/jobs/370737665

So I'm pretty sure that we need to improve or temporary disable it. Any chance that you know how to improve it?

**Comment by sanmai** [comment]
@sidz I'll look into it when I get to a machine where I can reproduce it.

**Comment by sidz** [comment]
@borNfreee are we happy to have a "random" fail?

**Comment by borNfreee** [comment]
> @borNfreee are we happy to have a "random" fail?

of course no.
but we can merge this PR (if it's ready) as it is not related to that fails, if you are speaking about it

**Comment by sidz** [comment]
yup we can. but maybe it'll be a good idea to take an approve from anybody else? @BackEndTea, @theofidry

**Comment by borNfreee** [comment]
Thank you @sidz and everyone else for the review!

**Pull request merged**
