### PR TITLE
feat: add support for sebastian/diff v6

### PR DESCRIPTION
**Pull request by simPod**
This PR:

- [x] Adds new feature ...
- [x] Covered by tests
- [ ] Doc PR: https://github.com/infection/site/pull/XXX

Adds support for sebastian/diff v6

### CODE REVIEW

**Comment by simPod** [comment]
Test failure is irrelevant. For some reason it install php-parser v5.

**Comment by maks-rafalko** [comment]
> For some reason it install php-parser v5.

it installs it because we don't specify any version of `php-parser` in e2e tests and we don't use Infection's `composer.json` there - we just depend on `phpunit` and it installs all the dependencies:

```
composer why nikic/php-parser 

phpunit/php-code-coverage 9.2.30 requires nikic/php-parser (^4.18 || ^5.0) 
sebastian/complexity      2.0.3  requires nikic/php-parser (^4.18 || ^5.0) 
sebastian/lines-of-code   1.0.4  requires nikic/php-parser (^4.18 || ^5.0)
```

since we have here `^4.18 || ^5.0` - by default composer for e2e test installs `nikic/php-parser:^5.0`.

It worked before, because API was the same among any of the 4.* version, and we were lucky that there weren't any issues like that before.

 Now, this is a problem. 

I don't really know what is the best way to handle it at the moment, but will try to think outloud

- we can add `nikic/php-parser: ^4.18` to all the `composer.json` files for all e2e tests and revert after https://github.com/infection/infection/pull/1909
- we can add `conflicts: `nikic/php-parser: >= 5.*` to all the `composer.json` files for all e2e tests and revert after https://github.com/infection/infection/pull/1909 (which is basically the same as above)
- we can wait until and revert after https://github.com/infection/infection/pull/1909 is merged and this will work again (well, by coinsidence)

@sidz do you have other ideas?

The issue is relevant when we use `bin/infection`, not `build/infection.phar` since it's prefixed and shouldn't conflict with `vendor`'s code.

**Comment by sidz** [comment]
The second option is looking fine from me @maks-rafalko.

**Review by sidz — APPROVED** [review]

**Comment by maks-rafalko** [comment]
Thank you @simPod

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/releases/tag/0.27.10

**Comment by simPod** [comment]
Thank you for finishing this.

**Pull request merged**
