### PR TITLE
Fix file not found exception for Codeception Cest `bug`

### PR DESCRIPTION
**Pull request by agilov**
For Codeception Cests there was TestFileNameNotFoundException because $fullyQualifiedClassName variable contains colon separated feature name but there is no .feature file in junit.xml report.

In  junit.xml  there is entries like so:

`<testcase file="/app/modules/site/controllers/ExampleErrorController_Cest.php" name="test400" class="app\modules\site\controllers\ExampleErrorController_Cest" feature="test400" assertions="3" time="0.010310"/>
`

And $fullyQualifiedClassName is like this `app\modules\site\controllers\ExampleErrorController_Cest:test400`

I think there is no need to open the issue for such a small bug and I've fixed it in my vendor directory and propose the change via pull request.

### CODE REVIEW

**Review by maks-rafalko — COMMENTED** [review]
Could you please 

1. add a test for this case
2. target 0.21 branch (if you want it to be released asap)

**Comment by agilov** [comment]
> Could you please
> 
> 1. add a test for this case
> 2. target 0.21 branch (if you want it to be released asap)

Added test case and changed branch. But I see conflict message "This branch has conflicts that must be resolved" for file I didn't touch. Is this my fault?

**Comment by maks-rafalko** [comment]
yes, this happened because master and 0.21 are different, unfortunately.

Could you please start your branch from 0.21 and cherry pick your commits? Or just make them again (shouldn't be hard).

So, as a result - we need to see only diff with your changes.

Regarding changes - cool. Will be happy to merge once diff is ready.

**Comment by agilov** [comment]
Started a new branch from 0.21, created this PR: https://github.com/infection/infection/pull/1503

**Pull request closed without merging**
