### PR TITLE
Enhancement: Implement ArgumentRemovalArrayReplace mutator

### PR DESCRIPTION
**Pull request by localheinz**
This PR

- [x] Adds new feature `ArgumentRemovalArrayReplace` mutator
- [x] Covered by tests
- [x] Doc PR: https://github.com/infection/site/pull/93

Related to #537.

### CODE REVIEW

**Comment by localheinz** [comment]
When I add the following test case

```diff
diff --git a/tests/Mutator/ArgumentRemoval/ArgumentRemovalArrayReplaceTest.php b/tests/Mutator/ArgumentRemoval/ArgumentRemovalArrayReplaceTest.php
index 69f96d2..b542f13 100644
--- a/tests/Mutator/ArgumentRemoval/ArgumentRemovalArrayReplaceTest.php
+++ b/tests/Mutator/ArgumentRemoval/ArgumentRemovalArrayReplaceTest.php
@@ -141,6 +141,30 @@ PHP
             ],
         ];

+        yield 'It mutates correctly when there is a backslash in front of array_replace' => [
+            <<<'PHP'
+<?php
+
+$a = \array_replace(['A', 1, 'C'], ['D']);
+PHP
+            ,
+            [
+                <<<'PHP'
+<?php
+
+$a = \array_replace(['D']);
+PHP
+                ,
+                <<<'PHP'
+<?php
+
+$a = \array_replace(['A', 1, 'C']);
+PHP
+                ,
+            ],
+        ];
+
+
         yield 'It mutates correctly when array_replace uses constants as input' => [
             <<<'PHP'
 <?php
```

and run

```
$  ./vendor/bin/phpunit tests/Mutator/ArgumentRemoval/ArgumentRemovalArrayReplaceTest.php
```

then the tests pass, but warnings are emitted:

```
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.22
Configuration: /Users/am/Sites/infection/infection/phpunit.xml.dist

......PHP Warning:  Unexpected character in input:  '' (ASCII=7) state=0 in - on line 3
PHP Warning:  Unexpected character in input:  '' (ASCII=7) state=0 in - on line 3
......                                                      12 / 12 (100%)

Time: 910 ms, Memory: 12.00MB

OK (12 tests, 46 assertions)
```

Does anyone have an idea how to sort this out?

**Comment by sanmai** [comment]
ASCII 7 aka Bell sneaked through somewhere?

**Comment by localheinz** [comment]
@sanmai 

Yes, right here:

https://github.com/infection/infection/blob/82904f46bbf47f2e222797171e94511e6442d759/tests/Mutator/AbstractMutatorTestCase.php#L167

**Comment by sanmai** [comment]
Well, that bit just checks if a test contains a valid PHP code. It is somewhere in `ArgumentRemovalArrayReplaceTest.php` or `ArgumentRemovalArrayReplace.php`

**Comment by localheinz** [comment]
@sanmai 

What do you think about 05639f3? 

Copied and adjusted from the examples at http://php.net/proc_open.

**Comment by sanmai** [comment]
It should be more like this: https://github.com/infection/infection/pull/301#issuecomment-380305627

Though I'm not entirely sure everything is in order there (proc_open is a bit tricky about closed-read pipes). So I'd make a separate function, and a test for it with a known invalid code.
```php
static function isCodeValid($code) { ... }
function test_is_code_valid_sees_invalid_code() {  $this->assertFalse(self::isCodeValid('<?php invalid=1')); }
function assertCodeValid($code) { $this->assertTrue(self::isCodeValid($code));  }

```

Original argument in #301 against `proc_open` was that it may not be supported on all platforms. But we use Symfony's Process which does require `proc_open` to be present, so that's not a very valid argument: if there's not a `proc_open` present, you can't even run Infection itself.

**Pull request closed without merging**
