### PR TITLE
fix: Do not increment max integer value (fixes #1484)

### LINKED ISSUE #1484: TypeError: Argument 1 passed to PhpParser\Node\Scalar\LNumber::__construct() must be of the type int, float given
| Question    | Answer
| ------------| ---------------
| Infection version | 0.21.0
| Test Framework version | PHPUnit 9.5.2
| PHP version | 7.4.15
| Platform    | Debian
| Github Repo | -

<details>
 <summary>Output with issue</summary>

Running initial test suite...

PHPUnit version: 9.5.2

  318 [============================] 7 mins

Generate mutants...

Processing source code files: 214/305PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\Node\Scalar\LNumber::__construct() must be of the type int, float given, called in /home/deepdiver/Development/......../vendor/infection/infection/src/Mutator/Number/IncrementInteger.php on line 81 and defined in /home/deepdiver/Development/......../vendor/nikic/php-parser/lib/PhpParser/Node/Scalar/LNumber.php:25
Stack trace:
#0 /home/deepdiver/Development/......../vendor/infection/infection/src/Mutator/Number/IncrementInteger.php(81): PhpParser\Node\Scalar\LNumber->__construct()
#1 /home/deepdiver/Development/......./vendor/infection/infection/src/Mutator/NodeMutationGenerator.php(143): Infection\Mutator\Number\IncrementInteger->mutate()
#2 /home/deepdiver/Development/......./vendor/infection/infection/src/Mutator/NodeMutationGenerator.php(112): Infection\Mutator\NodeMutationGenerator->generateForMutator()
#3 /home/deepdiver/Development/......../vendor/infection/infection/src/PhpParser/Visitor/MutationC in /home/deepdiver/Development/......../vendor/nikic/php-parser/lib/PhpParser/Node/Scalar/LNumber.php on line 25
</details>

### PR DESCRIPTION
**Pull request by DeepDiver1975**
This PR:

- [x] Covered by tests

Fixes https://github.com/infection/infection/issues/1484

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]
Looks good to me.

Could you please run `make cs` to fix style issues?

**Comment by DeepDiver1975** [comment]
> Could you please run `make cs` to fix style issues?

I tried .... see https://github.com/infection/infection/pull/1487 ;-)

**Comment by maks-rafalko** [comment]
Thank you @DeepDiver1975

**Comment by MidnightDesign** [comment]
The test won't work on a 32-bit system, will it?

**Comment by maks-rafalko** [comment]
> The test won't work on a 32-bit system, will it?

Looks like yes, see https://github.com/infection/infection/pull/1490

**Pull request merged**
