### PR TITLE
Enhancement: Implement GitHubActionsResolver

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] implements a `GitHubActionsResolver`

Related to #939.

❗️ Blocked by #1068.
💁‍♂ Also see https://github.com/infection/site/pull/155.

### CODE REVIEW

**Comment by localheinz** [comment]
@BackEndTea @maks-rafalko @sanmai @sidz @theofidry 

Perhaps we should keep this on hold and instead use [`ondram/ci-detector`](https://github.com/OndraM/ci-detector), as suggested by @Lctrs in https://github.com/infection/infection/pull/939#issuecomment-587501370?

What do you think?

**Comment by sanmai** [comment]
I think it is a great idea. I will be happy to use the same library for #1048.

**Comment by localheinz** [comment]
Closing in favour of using [`ondram/ci-detector`](https://github.com/OndraM/ci-detector).

**Comment by sanmai** [comment]
What do you think about opening an issue to track efforts towards implementing ondram/ci-detector?

**Comment by localheinz** [comment]
@sanmai 

Sounds good!

**Pull request closed without merging**
