### PR TITLE
Add support for `@infection-ignore-all` annotation

### PR DESCRIPTION
**Pull request by sanmai**
See #1231

This PR:

- [x] Adds a possibility to ignore an entire statement by commenting it with  `@infection-ignore-all`
- [x] Covered by an E2E test
- [x] Covered by unit tests
- [x] Doc PR: PR description can be used verbatim

Give this example Infection won't mutate or even look at anything inside this function:

```php
/** @infection-ignore-all */
public function doSomethingNastyButCostlyToRefactor() {

}
```

Likewise, given this annotation Infection won't consider anything in this loop:

```php
/** @infection-ignore-all */
foreach ($foo as $bar) {
    // 
}
```

### CODE REVIEW

**Comment by maks-rafalko** [comment]
LGTM

**Comment by sanmai** [comment]
@maks-rafalko This should auto-merge upon approval.

**Review by maks-rafalko — APPROVED** [review]
:+1: 

let's see how automerging works

**Comment by maks-rafalko** [comment]
image

hm... it says there was an error, but no information about it

**Comment by sanmai** [comment]
Can't get it working too.

**Comment by maks-rafalko** [comment]
@sanmai are you able to create a PR for docs please?

**Comment by sanmai** [comment]
Where do you think will be the best place to put it?

**Comment by maks-rafalko** [comment]
Probably, somewhere in the [Usage](https://infection.github.io/guide/usage.html) article. There we have information about other annotations like `@codeCoverageIgnore`.

**Comment by sanmai** [comment]
I'm not exactly sure these `@codeCoverageIgnore` annotations work as advertised, looking at the code. Let me check that they do, and if they don't we'll remove them and replace with `@infection-ignore-all` in this very section.

**Pull request merged**
