### PR TITLE
GitDiffFile: consume configured directories

### PR DESCRIPTION
**Pull request by Slamdunk**
This PR:

- [x] Fixes a bug
- [x] Covered by tests

Fixes https://github.com/infection/infection/pull/1368#discussion_r891152233

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]
Thank you!

It's not clear why MT action is failing, I think this is related to random mutants generated and not related to your changes. 

Could you please update `mt.yaml` to reduce MSI so this issue is resolved?

https://github.com/infection/infection/blob/62f52df22324a63102269dac4c1e03d7eed8b942/.github/workflows/mt.yaml#L14

(MSI for changed lines are 100% https://github.com/infection/infection/runs/6807209239?check_suite_focus=true#step:7:34)

**Comment by maks-rafalko** [comment]
Thank you @Slamdunk

**Comment by Slamdunk** [comment]
May I ask you a patch release for this merge? It would be very much appreciated :bowtie:

**Comment by maks-rafalko** [comment]
I will do it tonight

**Comment by maks-rafalko** [comment]
Released: https://github.com/infection/infection/releases/tag/0.26.11

**Pull request merged**
