### PR TITLE
Add While expression mutator

### PR DESCRIPTION
**Pull request by sidz**
This PR:

- [x] Adds new While expression mutator
- [x] Covered by tests
- [x] Schema needs an update
- [x] Doc PR: https://github.com/infection/site/pull/196

Mutates:
```diff
$condition = true;
- while ($condition) {
+ while (false) {
```

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]
Cool.

What about `do while()`? should we add similar mutator?

**Comment by sidz** [comment]
@maks-rafalko yes we should and I also have a plan to add it but it is not a ZeroIteration mutator. I'm thinking about deprecate zero_iteration profile in favor of loop (we also have Loop section in documentation).

But not sure how to achieve this with json schema validator so far. (found that latest shcema (https://json-schema.org/draft/2019-09/release-notes.html#meta-data-vocabulary) has "deprecated" property)

Or we may do it a bit aggressive and just rename `zero_iteration` profile to `loop` and realase in the next "major".

what do you think @maks-rafalko, @sanmai ?

**Comment by sanmai** [comment]
I'm for the rename. Next major assumes BC breaks, and that's what it is.

**Comment by sidz** [comment]
thanks @maks-rafalko , @sanmai

**Pull request merged**
