### PR TITLE
Enhancement: Allow to install sebastian/diff:^3.0

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] allows to install `sebastian/diff:^3.0`

### CODE REVIEW

**Comment by borNfreee** [comment]
Could you please rebase? :)

**Comment by localheinz** [comment]
@borNfreee 

Rebased!

**Comment by theofidry** [comment]
Needs to be rebased again :P

**Comment by sidz** [comment]
sorry ^_^

**Comment by localheinz** [comment]
@theofidry 

Rebased again!

**Comment by theofidry** [comment]
Let's merge that quickly before another rebased is required! Thanks for it @localheinz

**Comment by localheinz** [comment]
Thank you, @theofidry!

**Comment by localheinz** [comment]
@jakzal @theofidry 

Quick heads-up, the change was proposed because of https://github.com/sebastianbergmann/phpunit/commit/9497ffde7ec8c0d17ae80f01201b2834c56668a9, maybe we can get a release soon so we can use `infection/infection` with `phpunit/phpunit:^7.0.0`?

**Comment by borNfreee** [comment]
I will publich the release this weekend @localheinz

**Comment by borNfreee** [comment]
> maybe we can get a release soon so we can use infection/infection with phpunit/phpunit:^7.0.0

released under 0.7.1

**Comment by localheinz** [comment]
Thanks a ton, @borNfreee!

**Pull request merged**
