### PR TITLE
Use loaded ini settings

### PR DESCRIPTION
**Pull request by theofidry**
The original issue was reported by @sanmai in #252:

>right now `php -dmemory_limit=512M` infection has no effect on child processes

The issue is actually not specific to this peculiar parameter but any parameter overriden with the
`-d` option.

Indeed when building the temporary ini file, we are only looking at the settings coming from the
scanned files. Those settings however can be changed with the `-d` option. So provided you have:

```
// php.ini
param=X

// console
$ php -dparam=Y infection
```

We _should_ have in the temporary ini file `param=Y`.

<hr/>

Note that this issue is fixed by https://github.com/composer/xdebug-handler so we won't have this issue again when moving to it.

### CODE REVIEW

**Comment by sanmai** [comment]
This PR is all good, but this isn't a proper fix for the original issue #247. (PR #252 was superseded by the proposal #253.)

"Solving" #247 with this PR is like throwing out the champagne along with the cork. For one reason there's no evidence the Infection ever needed any kind of memory limits. Infection is a fine well written program, there's no need to limit its memory use so drastically.

**Comment by theofidry** [comment]
Yes it's not a patch for #247, I'm just saying this bug has been reported there nothing more :)

**Comment by sidz** [comment]
@theofidry I want to integrate https://github.com/composer/xdebug-handler instead of our custom handler. Maybe today or tomorrow :)

**Comment by borNfreee** [comment]
Since we have intergrated `xdebug-handler`, we don't have `src/Php/ConfigBuilder.php` anymore.

Is this PR still needed @theofidry ?

**Comment by theofidry** [comment]
Yes that should be fixed now!

**Pull request closed without merging**
