### PR TITLE
Enhacement: native function invocation cs fixer rule

### PR DESCRIPTION
**Pull request by BackEndTea**
This PR:

* [x] Adds the `native_function_invocation` rule
* [x] Runs `composer cs:fix`

>* **native_function_invocation**
Add leading ``\`` before function invocation of internal function to speed up resolving.
*Risky rule: risky when any of the functions are overridden.*
Configuration options:
> - ``exclude`` (``array``): list of functions to ignore; defaults to ``[]``

### CODE REVIEW

**Comment by sidz** [comment]
No a lot of sense to prefix all php functions. Here is the list of functions where it may be useful:
https://github.com/php/php-src/blob/f2db305fa4e9bd7d04d567822687ec714aedcdb5/Zend/zend_compile.c#L3872

**Comment by localheinz** [comment]
Also see https://wiki.php.net/rfc/fallback-to-root-scope-deprecation.

**Comment by borNfreee** [comment]
> No a lot of sense to prefix all php functions.

as far as I understand from [Nikic's comment](https://github.com/symfony/symfony/pull/25854#issuecomment-359185316), it's not useless  to prefix all functions

**Comment by theofidry** [comment]
👎  for me on that: it just makes the code way harder to read than it should.

IMO a more proper fix would be to import those functions/constants with use statements which for opcache or performance optimisations makes it strictly equivalent.

Now I'm aware there is no CS rule for this, but I think we should either wait or help for it, the perf. improvement we can get for this is too negligible for it right now at least.

Also note that this perf. improvement is only for non-PHAR usage as inside the PHAR PHP-Scoper will take care of this.

**Pull request closed without merging**
