### PR TITLE
Implement the Stryker HTML report

### LINKED ISSUE #1137: Add support for Stryker dashboard HTML report
As of now we are naming our badge logger "badge" because we make use of the minimal API to just get the badge with the mutation score.

Stryker dashboard however supports a full HTML report as well. The specifications can be found [here](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-report-schema).

For the configuration I propose two choices:

- A new logger (at the configuration level), e.g. `dashboard`
- Rename `badge` to `dashboard` or `stryker-dashboard` and have a setting `htmlReport: bool` with opt-in by default

### PR DESCRIPTION
**Pull request by theofidry**
Closes #1137

### CODE REVIEW

**Comment by theofidry** [comment]
@nicojs I'm making some progress here. Still very drafty but I got it to a point where I can generate the expected JSON and HTML to test the result.

There is definitely some adjustments to be made but I'm wondering why I can't see the mutations at all on the HTML report:

Screen Shot 2020-03-11 at 10 59 23

There is no JS error either... Do you have any idea?

**Comment by maks-rafalko** [comment]
> see [report.html](report.html)

link is broken

**Comment by theofidry** [comment]
Fixed

**Comment by nicojs** [comment]
@theofidry long story short: please try v1.3.1 😅

Thanks for all the work you're putting in!

**Comment by theofidry** [comment]
Thanks for looking into it :) Will try again

**Comment by maks-rafalko** [comment]
Closing in favor of https://github.com/infection/infection/pull/1625

Thank you for the initial work!

**Pull request closed without merging**
