### PR TITLE
Issue #644: Add the new unwrap mutator ucwords.

### PR DESCRIPTION
**Pull request by drupol**
This PR:

* [x] Adds new unwrap mutator ucwords
* [x] Covered by tests
* [x] Doc PR: https://github.com/infection/site/pull/119

Fixes: #644 

Related: #514

### CODE REVIEW

**Comment by drupol** [comment]
Sorry it's just an habit at work and other project. Basically it helps me finding a proper name for the branch :-)

**Comment by localheinz** [comment]
@drupol 

What do you think about adding a test case that shows that the mutator works correctly when the `$delimiter` parameter is present?

For reference, see http://php.net/manual/en/function.ucwords.php.

**Comment by drupol** [comment]
> @drupol
> 
> What do you think about adding a test case that shows that the mutator works correctly when the `$delimiter` parameter is present?
> 
> For reference, see http://php.net/manual/en/function.ucwords.php.

Ok will update the PR.

**Comment by borNfreee** [comment]
Thank you @drupol

**Pull request merged**
