### PR TITLE
Drop `symfony/*` below `5.4`

### PR DESCRIPTION
**Pull request by martinssipenko**
This PR:

Drops `symfony/*` below `5.4` and allows to install `6.x` versions of dev deps.

I created this as a follow-up of [#1693](https://github.com/infection/infection/pull/1693) where `symfony/filesystem` below `5.4` was dropped, if you think this is not necessary just close the PR.

### CODE REVIEW

**Comment by maks-rafalko** [comment]
> if you think this is not necessary just close the PR. 

The problem is that currently I don't know if this is necessary or not :) What is the main benefit of this update? Does it solve any issue?

**Comment by martinssipenko** [comment]
> What is the main benefit of this update?

The only benefit would be keeping things clean and consistent.

> Does it solve any issue?

Not that I know of.

**Review by Slamdunk — APPROVED** [review]

**Review by maks-rafalko — APPROVED** [review]
Ok, since Symfony <5.4 versions are not support anymore (except 4.4 LTS) and since users who still use outdated versions can use older Infection versions - I think it's good to go from my side.

@martinssipenko may I ask you to rebase and push? Thank you.

**Comment by maks-rafalko** [comment]
Thank you @martinssipenko

**Pull request merged**
