### PR TITLE
Make Infection installable with Composer 2

### PR DESCRIPTION
**Pull request by sanmai**
This PR:

- [x] Includes a backport of #1302
- [x] Includes partial backport of #1309
- [x] Allows Infection installation to proceed on PHP 7.3 with Composer 2.

For example, [you would see this error](https://github.com/kalimatas/php-liquid/pull/142/checks?check_run_id=1196368097#step:4:30).

### CODE REVIEW

**Review by maks-rafalko — APPROVED** [review]

**Comment by maks-rafalko** [comment]
CI [isn't happy](https://travis-ci.com/github/infection/infection/jobs/393995883#L335)

**Comment by sanmai** [comment]
Well, duh. I'll fix it.

**Comment by sanmai** [comment]
@maks-rafalko Should be release-ready.

**Comment by maks-rafalko** [comment]
https://github.com/infection/infection/releases/tag/0.17.6

Thank you @sanmai!

**Pull request merged**
