### PR TITLE
Add new `--git-diff-lines` option to generate Mutants only for the changed *lines*

### PR DESCRIPTION
**Pull request by maks-rafalko**
I've posted a question recently in twitter (https://twitter.com/infection_php/status/1475841561695072259) asking what is the  most wanted feature needed in Infection for developers.

One of the interesting feature request was to mutate only changed/added **lines** (note: currently in `master` as a minimum, we can mutate only added/changed **files** by `--git-diff-filter=AM`)

So, here is an implementation of the new option - `--git-diff-lines` that parsers `git diff` output, finds changed/added lines and filters out all mutants that are not for these lines.

This option automatically mutates only **A**dded and **M**odified files (`--git-diff-filter=AM` under the hood).

Useful to check how your changes impacts MSI in a feature branch. Useful for those who do not want / can't write tests for the whole legacy file, but wants to cover their own changes.

@Ocramius - this is your feature request, if you have some time, please help us testing on one of your projects. I've prepared a PHAR for this PR: 

[infection.phar.zip](https://github.com/infection/infection/files/7793116/infection.phar.zip)

### How to use (as an example):

```bash
infection.phar --git-diff-lines -j4  -s 
```

by default it does a diff with `master` branch, but this can be changed:

```bash
infection.phar --git-diff-lines --git-diff-base=main -j4  -s 
```

----

- [x] Doc PR: [TBD](https://github.com/infection/site/pull/228)

### CODE REVIEW

**Comment by guidobonuzzi** [comment]
Thanks, @maks-rafalko, this is fantastic! With this solution, I can check the MSI of my branch in less than 20 seconds instead of minutes.

Impressed!

I also tried the --git-diff-base option but it crashed with
```
In RunCommand.php line 420:
                                                            
  Cannot pass "--git-diff-base" without "--git-diff-filter"
```

**Comment by maks-rafalko** [comment]
> I also tried the --git-diff-base option but it crashed with

fixed! Here is a new PHAR

[infection.phar.zip](https://github.com/infection/infection/files/7794796/infection.phar.zip)

Happy new Year!

**Review by guidobonuzzi — APPROVED** [review]
👍

**Comment by maks-rafalko** [comment]
Thanks for testing it, @guidobonuzzi. Let's get it merged.

**Pull request merged**
