### PR TITLE
Split schema.json into root schema and mutators schema

### PR DESCRIPTION
**Pull request by sanmai**
This PR:

- [x] Splits schema.json into root schema and mutators schema
- [x] Should help make  other schemas

### CODE REVIEW

**Comment by maks-rafalko** [comment]
What is the final goal and how it will help, could you please clarify?

**Comment by sanmai** [comment]
Recall you had this problem with playground where there wasn’t a new mutant. And you told it uses a different schema for good reasons. So now you can include mutants.json into your custom schema, and largely forget about updating it.

**Comment by maks-rafalko** [comment]
> So now you can include mutants.json into your custom schema, and largely forget about updating it.

you mean using public URL and pointing to https://raw.githubusercontent.com/infection/infection/3dc1f8dd9dec65b258657f0c54569ae7b868459a/resources/mutators.json?

**Comment by sanmai** [comment]
This will be quite ineffective. If you're using Infection as a dependency you can include all mutators into another schema like so:
```json
 "$ref": "../vendor/infection/infection/resources/mutators.json#/mutators"
```

**Comment by sanmai** [comment]
Well, and you could actually do it like so, without this PR:
```
 "$ref": "../vendor/infection/infection/resources/schema.json#/mutators"
```

I'll have it closed for now.

**Pull request closed without merging**
