### PR TITLE
Upgrade to Php-parser 4.0

### PR DESCRIPTION
**Pull request by BackEndTea**
This PR:

- [x] Adds support for PHP-Parser 4.0
- [x] Covered by tests

### CODE REVIEW

**Comment by borNfreee** [comment]
fyi: there was some work in https://github.com/infection/infection/tree/php-parser-400 branch, I will dig into it later

**Comment by sidz** [comment]
imo we should drop 3.0 support.

**Comment by BackEndTea** [comment]
> imo we should drop 3.0 support.

We could, but i'd like to know how many people use infection as a dev dependency that also have a dependency on PHP-Parser

**Comment by borNfreee** [comment]
https://twitter.com/infection_php/status/969309000994041858

**Comment by theofidry** [comment]
@borNfreee if people are unhappy with it I think we could also mention bamarni/composer-bin-plugin and eventually [my article](https://medium.com/@tfidry/managing-your-dependencies-in-php-321d584441ab) about it

**Comment by borNfreee** [comment]
> https://twitter.com/infection_php/status/969309000994041858

let's drop 3.x

**Comment by theofidry** [comment]
Genuinely surprised by the amount of trollish answers :/

**Comment by BackEndTea** [comment]
> If 4.0 is used, we should use printFormatPreserving() rather than prettyPrintFile().

I have been playing around with that, but it causes all kinds of small inconsistencies. 

When running it on infection all diffs are this:
```diff
--- Original
+++ New
@@ @@
 
-declare(strict_types=1);
+declare (strict_types=1);
```

**Comment by borNfreee** [comment]
Then we need to post all such issues to PHP-Parser issue tracker.

Original reason of switching to 4.0 was saving formatting https://github.com/infection/infection/issues/55 (`Use PHP-Parser 4 to preserve mutated code formatting), because now files lose their code styles.

Of course, we can switch and don't use it, but what is our goal?

**Comment by BackEndTea** [comment]
> Of course, we can switch and don't use it, but what is our goal?

Then our goal would be to support projects that want to use both PHP-parser and infection as dev-dependencies.

**Comment by borNfreee** [comment]
I would suggest the following:

1. Move from 3.x to 4.x as it is new version, better performance, etc.
2. Drop support of 3.x as discussed above
3. do not use `printFormatPreserving()` at the moment because it's still not stable
4. from time to time post issues to PHP-Parser repository if we want eventually to activate `printFormatPreserving()`

**Comment by BackEndTea** [comment]
I've changed this to upgrade to 4.0, and drop support for 3.0. And it currently does not implement `printFormatPreserving()` due to previously mentioned issues.

**Comment by borNfreee** [comment]
Thank you @BackEndTea 👍

**Comment by BackEndTea** [comment]
Thank you @borNfreee, @theofidry & @sidz

**Comment by Sentoki** [comment]
https://github.com/infection/infection/pull/201/files#diff-3a47420a614944af649053250f50140fR102
We can have object in ast/Node name property? I have string with class name in this property and infection get error.

**Pull request merged**
