### PR TITLE
ci: Skip tests if Symfony6 & locked

### PR DESCRIPTION
**Pull request by theofidry**
Follow up of https://github.com/infection/infection/pull/1824#issuecomment-1487596531.

This PR is an attempt at reducing the jobs generated by the matrix.

### CODE REVIEW

**Comment by sidz** [comment]
Hey @theofidry
Do you have a chance to complete this PR?

**Comment by theofidry** [comment]
@sidz I can check that tonight I think

**Comment by sidz** [comment]
Thanks @theofidry. 

Just would like to say that I'm okay to pick it up, cherry-pick and re-create PR

**Review by sidz — APPROVED** [review]
:+1:

**Pull request merged**
