### PR TITLE
Add PHP 8.4 to the pipeline

### PR DESCRIPTION
**Pull request by sidz**
This PR adds PHP 8.4 into pipeline.

### CODE REVIEW

**Comment by sidz** [comment]
Seems like we need to wait next composer release with updated `justinrainbow/json-schema`. So composer stop producing deprecation notes.

**Review by sanmai — APPROVED** [review]
Nice!

**Comment by sidz** [comment]
Ready for review @infection/core

**Review by maks-rafalko — APPROVED** [review]
👍

**Comment by sidz** [comment]
thanks @maks-rafalko, @sanmai

**Pull request merged**
