### PR TITLE
Use stable thecodingmachine/safe

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by theofidry** [comment]
why not pushing for the beta only instead of allowing `^0.1` as well?

**Comment by sidz** [comment]
do we really would like to use library in the beta/alpha version stage? @theofidry @maks-rafalko

**Comment by maks-rafalko** [comment]
> do we really would like to use library in the beta/alpha version stage?

Well, although we are safe since we are using `composer.lock` file, I would still avoid using beta versions as a direct dependencies in Infection.

As I understand, @snapshotpl wants to be able to install Infection to his project, where `1.0.0.@beta` is already used. 

What if I suggest you using Infection PHAR distribution instead and forget about conflicted dependencies ;) ?

**Comment by snapshotpl** [comment]
@maks-rafalko that's great idea, however it's not simple to install and maintain infection's phar like [phpstan](https://github.com/phpstan/phpstan) or [rector](https://github.com/rectorphp/rector-prefixed)

**Comment by sidz** [comment]
What is difference between phar for phpstan and infection?

ср, 11 дек. 2019 г., 10:26 Witold Wasiczko <notifications@github.com>:

**Comment by snapshotpl** [comment]
I can download phpstan as phar via composer

**Comment by theofidry** [comment]
>I would still avoid using beta versions as a direct dependencies in Infection.

In this specific case we use the dev version (0.1) which is not any safer than a beta

**Comment by maks-rafalko** [comment]
What is the benefit to use PHAR through composer rather than just download it or use https://phar.io/ to manage PHARs?

**Comment by snapshotpl** [comment]
I don't need to change nothing in my project. Like phpstan did in 0.12. After composer install I just get phar. In your case in need to change my local and production deployment process.

**Comment by theofidry** [comment]
@snapshotpl any chance to do a `composer update`? Would love to get this one merged :)

**Comment by snapshotpl** [comment]
@theofidry  `thecodingmachine/safe` is now in stable version :)

**Comment by theofidry** [comment]
Thank you @snapshotpl

**Pull request merged**
